/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mayaSpiegelEngine */

#ifndef _Included_mayaSpiegelEngine
#define _Included_mayaSpiegelEngine
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     mayaSpiegelEngine
 * Method:    addParticleCluster
 * Signature: ([C[[DI)Z
 */
JNIEXPORT jboolean JNICALL Java_mayaSpiegelEngine_addParticleCluster
  (JNIEnv *, jobject, jcharArray, jobjectArray, jint);

/*
 * Class:     mayaSpiegelEngine
 * Method:    addParticleClusters
 * Signature: ([[C[[[D[II)Z
 */
JNIEXPORT jboolean JNICALL Java_mayaSpiegelEngine_addParticleClusters___3_3C_3_3_3D_3II
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jintArray, jint);

/*
 * Class:     mayaSpiegelEngine
 * Method:    addParticleClusters
 * Signature: ([[C[[[D[I[[[DI)Z
 */
JNIEXPORT jboolean JNICALL Java_mayaSpiegelEngine_addParticleClusters___3_3C_3_3_3D_3I_3_3_3DI
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jintArray, jobjectArray, jint);

/*
 * Class:     mayaSpiegelEngine
 * Method:    removeParticleCluster
 * Signature: ([C)Z
 */
JNIEXPORT jboolean JNICALL Java_mayaSpiegelEngine_removeParticleCluster
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     mayaSpiegelEngine
 * Method:    removeParticleClusters
 * Signature: ([[C)Z
 */
JNIEXPORT jboolean JNICALL Java_mayaSpiegelEngine_removeParticleClusters
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     mayaSpiegelEngine
 * Method:    getNumOfParticleClusters
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_mayaSpiegelEngine_getNumOfParticleClusters
  (JNIEnv *, jobject);

/*
 * Class:     mayaSpiegelEngine
 * Method:    getParticleClusterNames
 * Signature: ()[[C
 */
JNIEXPORT jobjectArray JNICALL Java_mayaSpiegelEngine_getParticleClusterNames
  (JNIEnv *, jobject);

/*
 * Class:     mayaSpiegelEngine
 * Method:    getParticlePositions
 * Signature: ([C)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_mayaSpiegelEngine_getParticlePositions
  (JNIEnv *, jobject, jcharArray);

/*
 * Class:     mayaSpiegelEngine
 * Method:    changeParticleIncandesense
 * Signature: ([C[[D)Z
 */
JNIEXPORT jboolean JNICALL Java_mayaSpiegelEngine_changeParticleIncandesense
  (JNIEnv *, jobject, jcharArray, jobjectArray);

/*
 * Class:     mayaSpiegelEngine
 * Method:    changeParticlePositions
 * Signature: ([C[[DI)Z
 */
JNIEXPORT jboolean JNICALL Java_mayaSpiegelEngine_changeParticlePositions___3C_3_3DI
  (JNIEnv *, jobject, jcharArray, jobjectArray, jint);

/*
 * Class:     mayaSpiegelEngine
 * Method:    changeParticlePositions
 * Signature: ([[C[[[D[II)Z
 */
JNIEXPORT jboolean JNICALL Java_mayaSpiegelEngine_changeParticlePositions___3_3C_3_3_3D_3II
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
